<?php

declare(strict_types=1);

namespace Ujwaldhakal\Messenger;

use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\HttpKernel\Bundle\Bundle;
use Ujwaldhakal\Messenger\DependencyInjection\MessengerExtension;

final class MessengerBundle extends Bundle
{
    public function getPath(): string
    {
        return __DIR__;
    }

    public function build(ContainerBuilder $container)
    {
        parent::build($container); // TODO: Change the autogenerated stub
        $container->registerExtension(new MessengerExtension());
    }
}
